### ISSUE TITLE
Auto Remove Deps

### ISSUE THREAD

**Issue by TheMulhima** [TheMulhima/Scarab#12]
### Explanation of the new feature

Auto-remove all dependencies that were not installed by the user. 
This would mean
- marking mods as user installed
- a prompt to tell which mods are going to be removed
- a toggle for it because it's going to be opt-in

**Comment by TheMulhima** [comment]
Probably will wait until:
- #4 so that the tab system can be added to the UI 
- #6 so people can mark important mods and not worry it will be auto deleted

**Comment by TheMulhima** [comment]
Probably will wait until:
- #4 so that the tab system can be added to the UI 
- #6 so people can mark important mods and not worry it will be auto-deleted

**Comment by JacksonFaller** [comment]
What if we display a list of all unused dependencies as a check list (with nothing selected by default), and user can choose what needs to be uninstalled.
