### ISSUE TITLE
Unable to Open on Mac (Scroll Down for Answer)

### ISSUE THREAD

**Issue by menmoe** [TheMulhima/Scarab#129]
### Lumafly Version

v3.3.0.0

### Hollow Knight Version

N/A

### Steps to Reproduce

On the latest version of MacOS (Sequioa 15.0.1), I am unable to open the app. When I try it says "Apple could not verify Lumafly of malware that may harm your Mac or compromise your privacy." It then gives me the option "Done," which closes the app, or "Move to Trash," which deletes the app. I have scanned the app with Norton and there doesn't seem to be any concerns.

When apps don't open on Mac, say due to "unidentified developer," you can usually right click the app and it will give you the same prompt with the option to open anyways. That is not the case here.

This may just be a problem with Apple, but I only started experiencing this when I downloaded the latest version of Lumafly (v3.3.0.0).

### Expected Behaviour

I expected the app to open

### Actual Behaviour

It gave me the above-mentioned error 

### Errors and Logs

[ModInstaller.log](https://github.com/user-attachments/files/17356854/ModInstaller.log)

The error should be around 10-15 lines from the bottom.

**Comment by DwarfWoot** [comment]
It sounds like what you tried was slightly different from the steps in familiar with, so you may want to try this:

- In the `Finder`  on your Mac, locate the app you want to open. *Don’t use Launchpad to do this! It doesn’t allow access the shortcut menu.*
- `Control` + `click` the app icon, then choose "Open" from the shortcut menu.
- `Click` "Open".
**Note**: You may need to do this **twice**, as the "Open" button doesn’t always appear the first time.
*The app is now saved as an exception to your security settings, and you can open it in the future by double-clicking it like normal.*

**Comment by moishy-r** [comment]
I tried this too, it didn't work.

But after clicking on the little "**?**" button on the top corner of the error message (I think that's new, I've never noticed it before), I learned the fix:
  - (After closing the error message,) open **System Settings** > **Privacy and Security**.
  - Scroll all the way down where it says **Security**. You should see there the app that was blocked and an option to '**open anyways**'.

I guess **MacOS Sequioa**'s new security system caught me off guard.
