### ISSUE TITLE
[ModInstaller_Error_46-05-15 15-29-31.log](https://github.com/user-attachments/files/17790982/ModInstaller_Error_46-05-15.15-29-31.log)

### ISSUE THREAD

**Issue by xmarzero** [TheMulhima/Scarab#132]
### Lumafly Version

v3.3.0.0

### Hollow Knight Version

v1.5

### Steps to Reproduce

[ModInstaller_Error_46-05-15 15-29-31.log](https://github.com/user-attachments/files/17790982/ModInstaller_Error_46-05-15.15-29-31.log)

### Expected Behaviour

[ModInstaller_Error_46-05-15 15-29-31.log](https://github.com/user-attachments/files/17790984/ModInstaller_Error_46-05-15.15-29-31.log)

### Actual Behaviour

[ModInstaller_Error_46-05-15 15-29-31.log](https://github.com/user-attachments/files/17790985/ModInstaller_Error_46-05-15.15-29-31.log)

### Errors and Logs

[ModInstaller_Error_46-05-15 15-29-31.log](https://github.com/user-attachments/files/17790987/ModInstaller_Error_46-05-15.15-29-31.log)

**Comment by Ruttie2006** [comment]
Pirated game installs are not supported.
