### ISSUE TITLE
Align Enable, Update and Install buttons to the right, and improve Update button visual

### ISSUE THREAD

**Issue by Geroyuni** [TheMulhima/Scarab#38]
### Explanation of the new feature

The buttons to the right of each mod name can currently stick close to the left enough that they force mod names into taking two lines, even though there's a lot of white space to the right of the buttons.

![image](https://github.com/TheMulhima/Scarab/assets/6061850/81a53124-d47d-490e-b67d-e55d01c0df59)

The suggestion is to attach them to the right, which seems similar to what 'Search Options' does. The update button column could persist if there's no update button or preferably just be hidden.

![image](https://github.com/TheMulhima/Scarab/assets/6061850/31e541be-bf8f-4295-a585-f7bcc462c5b0)

As a separate suggestion, I experimented with replicating the look of the Install buttons for the Update button, which seems to also make the UI more coherent. I'm using a [material icon](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:update:FILL@0;wght@400;GRAD@0;opsz@48&icon.query=update) for the above example.

**Comment by TheMulhima** [comment]
How is this
<img width="566" alt="image" src="https://github.com/TheMulhima/Scarab/assets/81007262/de6c2888-d19e-4cbf-ae63-ee427a260fcb">
