### ISSUE TITLE
Font Fallbacks not working

### ISSUE THREAD

**Issue by lxymahatma** [TheMulhima/Scarab#53]
### Scarab Version

v2.2.0.1 (main branch latest)

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

I saw you've add more font names in font overrides, but seems like the font fallback is not working.

Basically i don't have the first font installed on my computer, the Source Han Sans SC, theoretically it should causes the loading error and try the following fonts, but i have Microsoft YaHei, Arial, 黑体, 楷体 etc installed. The program still cannot launch without moving the font i've installed on my computer to be the first one.

I'm not sure why it's happening, maybe it's avalonia side font fallback problem(?
cz i checked the fontfallbacks list seems to be fine

### Expected Behaviour

Application launch

### Actual Behaviour

Failed to launch

### Errors and Logs

null

**Comment by TheMulhima** [comment]
Hopefully someone on the Avalonia team and resolve it

**Comment by TheMulhima** [comment]
could you download latest master again and see if the font loaded works and is the noto sans font
https://themulhima.github.io/Scarab/?download=latest

**Comment by lxymahatma** [comment]
> could you download latest master again and see if the font embedding works and the displayed font is the noto sans font https://themulhima.github.io/Scarab/?download=latest

yeah it's working 👍
![image](https://github.com/TheMulhima/Scarab/assets/66151783/f1660e8f-e045-4a9c-84a9-aec47a55373b)
