### ISSUE TITLE
Offline Mode

### ISSUE THREAD

**Issue by ToboterXP** [TheMulhima/Scarab#8]
### Explanation of the new feature

Ability to enable and disable mods while offline (for example by saving the most recent version of modlinks that was processed)

**Comment by TheMulhima** [comment]
>  by saving the most recent version of mod links that was processed
Ideally, it would save it only so that it can show mod info for mod links mods

**Comment by TheMulhima** [comment]
Additional Notes:
- Need to handle cases where a mod has been disabled and has 1 or more of its dependencies missing, and in offline mode it's attempting to be enabled
